### ISSUE TITLE
Question: How run Job on Different VM Worker?

### ISSUE THREAD

**Issue by adewahyu123** [pivotal-cf/bbr-pcf-pipeline-tasks#19]
Please help me, i want to backup two environtment. Let say Prod and Dev. I have 2 instance Worker. On dev will use one VM worker and Prod will use another one. How to achieve this setting. Because i dont have and idea related to concourse worker tags. Is there any good documention for adding worker tags ?

**Comment by findneville** [comment]
If both your VM workers are the same configuration, you can skip the concourse worker tag. 

In our environment, we do not have tagged concourse workers. So we remove that reference from our pipelines, which means the jobs will pick any worker that is available. Now the reason for the tagging is because you may need more space for backing up all of your CF director and ERT. 

If you do have specific concourse tagged workers defined, you can easily create either two separate pipelines or use mustache to backup both environments within a single pipeline.

**Comment by glestaris** [comment]
hey @adewahyu123, I'll close this. Feel free to re-open if you have further questions.
