### ISSUE TITLE
Non-versioned file option?

### ISSUE THREAD

**Issue by sethlindberg** [pivotal-cf/bbr-pcf-pipeline-tasks#2]
I'm working on a concourse pipeline using this for an s3-compatible filestore but one that doesn't support versioned files.  Is there a way to set up the s3 resource part of the pipeline without versioned files?

**Comment by henryaj** [comment]
Hi @sethlindberg. Using non-versioned S3 resources is definitely possible. You'd need to update the tasks so that their outputs have unique filenames – by e.g. changing the [`tar` command](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/f9b9e98dc0dfbb27522ca9f8932a9ea88ba6004a/tasks/bbr-backup-ert/task.sh#L12) to include a timestamp.

You'd also want to change the `put` part of each job in the pipeline to use a regex instead of a [fixed filename](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/f9b9e98dc0dfbb27522ca9f8932a9ea88ba6004a/pipeline.sample.yml#L59).

**Comment by henryaj** [comment]
Let us know if you need anything else!
