### ISSUE TITLE
Consideration: Add a site-id parameter to identify what site installation.zip belongs to

### ISSUE THREAD

**Issue by findneville** [pivotal-cf/bbr-pcf-pipeline-tasks#22]
This might be my view but here it goes. 

It is common for CF teams to have a single bucket for all backups.

Given the current pipeline if you run the backups for say export-om-installation for two sites keeping the s3 bucket the same, the installation.zip of one site will be overwritten by the installation.zip of the other site since there is no uniqueness in the name. This can happen for director and ert backups too. It works amazingly well as long as it is for one site and one site only. 

My suggestion is to add a site-id parameter that consumers can add to the secrets and the site-id will be appended to the versioned file as ((site-id))-installation.zip . This is something that requires modification of  the pipeline.yml only. 

As much as consumers can customize the existing pipeline to their needs, this might be one that ensures files are named meaningfully when the pipeline is run. 

If there is interest, I can submitted a PR for the same.

**Comment by ChunyiLyu** [comment]
Hi @findneville,

You are totally right that if two foundations are using the backup pipeline and sharing the same s3 bucket, backup artifacts would overwrite themselves. If I am understand the issue correctly, the issue is that when storing backup artifacts from multiple sites in the same s3 bucket, their artifacts overwrite themselves, and became hard to distinguish. To solve this issue, we can see several different approaches. 

The s3 concourse resources supports uploading to a specific path of the bucket by specifying the param `versioned_file`. We can update our sample pipeline definition to take the path to upload as user inputs. 

An approach to solving the issue of artifacts overwriting themselves (even from the same site), would be to include a timestamp in the artifact filename. Do you think this would also be of value? 

These two approaches are not mutually exclusive, and we could consider implementing both if you think they would be of value.

Cheers,
Chunyi && Mirah

**Comment by glestaris** [comment]
Closing for now due to inactivity. Please reach out to us (reopen) if the above suggestions are not suitable for your use case and we can chat some more.

Thanks Neville.
