### ISSUE TITLE
bbr precheck before doing backup

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal-cf/bbr-pcf-pipeline-tasks#59]
In the documentation for backing up PCF https://docs.pivotal.io/pivotalcf/2-6/customizing/backup-restore/backup-pcf-bbr.html#check-director, the "Check Your BOSH Director" section says to call `bbr backup-pre-check` . 

A customer has this as part of their cron bbr backup process that we are moving to concourse. We created the tasks and scripts to support it and added it to the director backup job. The idea is that the backup precheck will fail and kill the backup job before any of the other backup steps run. 

Creating this issue to see if this is a desirable contribution for a pull request.

**Comment by aclevername** [comment]
Hello @patrick-huber-pivotal,

If I'm understanding you correctly you are asking wether having a new task that runs a `bbr pre-backup-check` would be useful? If so I think the answer is no, this is because as part of doing `bbr backup` it runs the equivalent of a `pre-backup-check` before it starts taking the backup. So in essence as part of doing `bbr backup` you are already gaining all the validity of running a `pre-backup-check`

**Comment by patrick-huber-pivotal** [comment]
Ok, thanks. That makes sense and based on what you are saying I don't see a
need to run precheck before doing the backup.

**Comment by aclevername** [comment]
@patrick-huber-pivotal cool. Unless you have any other questions I am going to close this issue :)

Cheers,
Jake
