### ISSUE TITLE
Compressing the pas and director backup

### ISSUE THREAD

**Issue by meraj-kashi** [pivotal-cf/bbr-pcf-pipeline-tasks#77]
Hi,

I have a query about adding compression option in the tasks under `bbr-backup-pas` and `bbr-backup-director`. Is there any logic behind the current scripts which only archive the files or is it possible to add compression option? 

For example:
 tar -czvf "director-backup_${current_date}.tar.gz" --remove-files -- */*

Thanks,
Meraj

**Comment by neil-hickey** [comment]
Hey there @meraj-kashi , apologies for the very late reply on this one. 

I am not aware of any reason that the `-z` flag could not be added. The only thing I could think is that this task backs up using BBR, and the expectation is the file is valid for restoring. I am not sure if BBR accepts a gzip'ed archive or not.

@totherme / @kirederik / @pivotal-cf/cryogenics  does anyone have any other insights?

**Comment by totherme** [comment]
I suspect that the reason the `-z` flag isn't already there is because:
- the thing we're putting in the new tar file is the backup directory we just created
- that backup directory exclusively contains existing `.tgz` files (one for each bosh job that has been backed up), which have already been compressed
- ...so asking `tar` to compress them again won't gain us anything.

**Comment by neil-hickey** [comment]
That makes alot of sense @totherme ! Thanks for that 👍 

@meraj-kashi hopefully that makes sense, I am going to close out this issue for now and if you have any other queries feel free to open another / reopen this one.
